development:
  password: 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
  theme_id: "109193855129"
  store: sm-shop-ph.myshopify.com

production:
  password: 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
  theme_id: "107507056793"
  store: sm-shop-ph.myshopify.com